### ISSUE TITLE
Having one edit profile use case, or splitting them up into two separate use cases (edit bio and edit Spotify handle)

### ISSUE THREAD

**Issue by zfjuliana** [not-ryan-ning/Friendify#25]
When a user performs the edit profile use case, it takes them to an edit profile view where they can edit the fields for bio and Spotify handle via one save button. Currently, I have two separate use cases for edit bio and edit Spotify handle. However, would I still need an overall edit profile use case that chooses which one to invoke? On the other hand, since there is only one save button, should I simply have if statements in an edit profile use case that checks which field was changed and calls the appropriate methods?

**Comment by ShihHsin0723** [comment]
Solved
