### ISSUE TITLE
Treating LoggedIn as a use case or not?

### ISSUE THREAD

**Issue by oliviaw12** [not-ryan-ning/Friendify#27]
Currently, I am implementing the logged in view, which acts as our main homepage. In this Logged In View, there are buttons like friends, requests, edit profile, match and logout, which on click, brings the user to the relevant view. Because LoggedInView is just changing views based on what button the user clicks, do you think Logged In should be a use case or should we be treating this as a view?

**Comment by ShihHsin0723** [comment]
Solved
