### ISSUE TITLE
Implementation of the two display profile views for common user and friends. 

### ISSUE THREAD

**Issue by oliviaw12** [not-ryan-ning/Friendify#29]
I am currently implementing the View for the DisplayProfile use case.  The main feature we are planning on implementing for this is that a user is either brought to a Common user profile view or a friend user profile view, depending on the user's relationship with the other user they would like to view. However, since these two have slightly different displays, should we be passing in a User object into our View class to directly access the relevant details for profile and combine the two classes or have two separate views?

**Comment by ShihHsin0723** [comment]
Solved
