### ISSUE TITLE
Implementation of the matching (matching attributes) use case 

### ISSUE THREAD

**Issue by not-ryan-ning** [not-ryan-ning/Friendify#35]
I've implemented the matching attributes use case, but I'm using a hashmap instead of an ArrayList to consider the frequencies of attributes coming up, and to optimize the running time of the program. I think this implementation is more efficient - could someone double check my implementation in my branch and confirm whether or not we should switch to a HashMap implementation?

**Comment by ShihHsin0723** [comment]
Solved
